# Generated by Django 5.1.5 on 2025-01-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eventos_riesgos_js",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField()),
                ("involucrados", models.IntegerField()),
                ("duracion", models.IntegerField()),
                ("url_imagen", models.TextField()),
                ("sector", models.CharField(max_length=100)),
                ("factor_riesgo", models.TextField()),
                ("video", models.TextField(blank=True, null=True)),
                ("ancho_imagen", models.IntegerField(blank=True, null=True)),
                ("alto_imagen", models.IntegerField(blank=True, null=True)),
                ("video_generado", models.BooleanField(default=False)),
                ("revisado", models.BooleanField(default=False)),
                ("baja_probabilidad", models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
