# Generated by Django 5.1.5 on 2025-01-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventos_riesgos_js",
            options={"managed": False},
        ),
    ]
