# Generated by Django 5.1.5 on 2025-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_eventos_riesgos_js_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="coords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_foto", models.TextField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("clase", models.TextField()),
            ],
            options={
                "db_table": "coords",
                "managed": False,
            },
        ),
        migrations.AlterModelTable(
            name="eventos_riesgos_js",
            table="eventos_riesgos_js",
        ),
    ]
